### ISSUE TITLE
Application errors when viewing new tickets

### ISSUE THREAD

**Issue by jimmie-jam** [Peppermint-Lab/peppermint#338]
I cant seem to figure this out. I have a fresh instance of Ubuntu server 22.04 and Peppermint.sh. When I (an admin), create a new ticket, I can edit the ticket, update and close it. When I use the guest portal, or create a standard user and submit a ticket, then try to edit it as my admin user account, the ticket errors with a generic, "The page has experienced a error," message.  

Any thoughts? 

Thanks!

**Comment by potts99** [comment]
will look now @jimmie-jam

**Comment by jimmie-jam** [comment]
> will look now @jimmie-jam

Hey @potts99,

Here is a more specific error. This is what I see when I create a ticket through the Guest Portal URL, and then try to view the ticket as an admin user, while logged in. 

Application error: a client-side exception has occurred (see the browser console for more information).

Thanks for the help!

**Comment by potts99** [comment]
Thanks @jimmie-jam that helps a lot

**Comment by wildan82** [comment]
same here

Application error: a client-side exception has occurred (see the browser console for more information).

Error: initialContent must be a non-empty array of blocks, received: title

**Comment by potts99** [comment]
is this on all tickets or tickets via the guest portal? @wildan82 @Mo187

**Comment by potts99** [comment]
@Mo187 @wildan82 @jimmie-jam pushing a build that should help fix this error

**Comment by jimmie-jam** [comment]
> @Mo187 @wildan82 @jimmie-jam pushing a build that should help fix this error

Awww yeah! Thanks, @potts99!

**Comment by potts99** [comment]
fixed? @jimmie-jam

**Comment by Mo187** [comment]
Hey @potts99  its fixed. thank you very much. There's another issue though which i noticed on day 1 of using peppermint, when you click on different tickets to view them it will often display the wrong ticker title and number. I have reproduced this multiple times. For example : on these two screenshots you can see that the ticket with laptop is #1 but when i click on the email ticket #2 this is what it shows.
![Screenshot 2024-06-23 123440](https://github.com/Peppermint-Lab/peppermint/assets/17753184/d22f657f-7f08-418a-8391-4c4e50060695)
![Screenshot 2024-06-23 123554](https://github.com/Peppermint-Lab/peppermint/assets/17753184/0d78c563-0d43-4901-919a-b26f03037a70)

**Comment by potts99** [comment]
This is likely a caching issue @jimmie-jam, will take a look

**Comment by jimmie-jam** [comment]
> fixed? @jimmie-jam

Same issue. I did a full reinstall with docker-compose and pulled all the updated files, but I received the same error. It only happens when I use the Guest Portal though.

**Comment by aclebre** [comment]
I'm having the same issue. I, as the admin, can't edit, assign, or practically do anything with tickets after they are created. Even when I create them as the admin I still can't access them. When I click on any part of the ticket it gives me the "Application error: a client-side exception has occurred (see the browser console for more information)."
I'm running peppermint in Linode if that makes a difference.

**Comment by Spectroxx** [comment]
I am also experiencing the same issue. It seems when a ticket is created via the Guest Portal URL, no one is assigned the ticket that is generated and even the admin user is not able to view/manage the ticket.

**Comment by partha51613** [comment]
I am still getting this error
